In [1]:
import numpy as np

In [4]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Vector:",array2)
a=array2.reshape(3,5)
print("Two dimensional array:",a)

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Two dimensional array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
print("shape:",a.shape)
print("dimension:",a.ndim)
print("data type:",a.dtype.name)
print("size:",a.size)
print("type:",type(a))

shape: (3, 5)
dimension: 2
data type: int32
size: 15
type: <class 'numpy.ndarray'>


In [6]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x==2)

[5 7 9]
[-3 -3 -3]
[False  True False]


In [7]:
a=np.array([1,2,3])
d=a.copy()
print(d)
b=a
c=a
b[0]=5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


In [8]:
a=np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [9]:
reverse_array = a[::-1]
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [10]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [12]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,1])
print(b[:1])
print(b[1:])
print(b[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[7 8 9]
